### ISSUE TITLE
include @since tags in replace (createmodulefromskeleton.py)

### ISSUE THREAD

**Issue by Praesidiarius** [OnePlc/PLC_X_Skeleton#4]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

The version gets reset to 1.0.0 by script, but not the comments. also search and replace
for the 1.0.6 (or defined version) and replace by 1.0.0

See Module.php @since tag for const VERSION

**Comment by JBinggi** [comment]
Problem fixed
39d3dd5
